apiVersion: v1
kind: Service
metadata:
  name: ch-bff-service
  namespace: {NAMESPACE}
  labels:
    app: ch-bff
spec:
  selector:
    app: ch-bff
  ports:
  - port: 9300
    protocol: TCP
    targetPort: 9300
  type: LoadBalancer


