logging:
  level:
    com:
      tootest:
        ch: DEBUG
    org:
      springframework:
        web: INFO
    root: INFO

server:
  port: 9300
  servlet:
    context-path: /ch-bff
ch:
  user:
    host: localhost
opentracing:
  spring:
    web:
      enabled: false
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
