ch:
  user:
    host: user-service


logging:
  pattern:
    console: '%d{ABSOLUTE} [%X{traceId}/%X{spanId}] [%X{EagleEye-TraceID}] %-5p [%t] %C{2} - %m%n'

opentracing:
  spring:
    cloud:
      log:
        enabled: false
occ:
  tracer:
    enabled: true
    service-name: tootest_ch_bff