logging:
  level:
    com:
      tootest:
        ch: DEBUG
    org:
      springframework:
        web: INFO
    root: INFO
  file:
    path: /
    name: ch-bff.log

server:
  port: 9300


ch:
  user:
    host: localhost
opentracing:
  spring:
    web:
      enabled: false
