spring:
  autoconfigure:
    exclude: io.opentracing.contrib.spring.tracer.configuration.TracerAutoConfiguration


ch:
  user:
    host: localhost
opentracing:
  spring:
    web:
      enabled: false
