logging:
  level:
    com:
      tootest:
        ch: DEBUG
    org:
      springframework:
        web: INFO
    root: INFO

server:
  port: 9300
  servlet:
    context-path: /ch-bff

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
