apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: "lb-uf60e51dfzm6lzye1chhb"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-force-override-listeners: "true"
  name: bff-service
  namespace: {NAMESPACE}
  labels:
    app: bff
spec:
  selector:
    app: bff
  ports:
  - port: 9212
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
